# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: "Az CLI login"
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZ_CREDS }}

      # - name: Azure CLI script
      #   id: get_deployment_key
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #       APIKEY=$(az staticwebapp secrets list --name nest-settings-app --query "properties.apiKey")
      #       #echo "::add-mask::$APIKEY"
      #       echo "apikey=$APIKEY" >> $GITHUB_OUTPUT

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          #azure_static_web_apps_api_token: ${{ steps.get_deployment_key.outputs.apikey }}
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "swa-next" # App source code path relative to repository root
          output_location: "out" # Built app content directory, relative to app_location - optional
        env:
          is_static_export: true          
